---
title: "521 Project 2"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(viridis)
library(GGally)

# graph theme object 
theme_settings <- theme_light() + theme(axis.text = element_text(size=8), axis.title = element_text(size = 9), legend.title = element_text(size = 9), plot.title = element_text(size = 10, hjust = 0.5)) 
```

## Section 1 

&nbsp; 

```{r}
# read in files with column names 
names <- c("y_coord", "x_coord", "expert", "ndai", "sd", "corr", "angle_df", 
           "angle_cf", "angle_bf", "angle_af", "angle_an")

imagem1 <- read.table('./data/imagem1.txt', col.names = names)
imagem2 <- read.table('./data/imagem2.txt', col.names = names)
imagem3 <- read.table('./data/imagem3.txt', col.names = names)


# make expert column factor and text version
imagem1 %>%
  mutate(expert = as.factor(expert)) %>%
  mutate(expert_text = ifelse(expert == 0, "unlabeled", ifelse(expert == 1, "cloudy","clear"))) -> imagem1

imagem2 %>%
  mutate(expert = as.factor(expert)) %>%
  mutate(expert_text = ifelse(expert == 0, "unlabeled", ifelse(expert == 1, "cloudy","clear"))) -> imagem2

imagem3 %>%
  mutate(expert = as.factor(expert)) %>%
  mutate(expert_text = ifelse(expert == 0, "unlabeled", ifelse(expert == 1, "cloudy","clear"))) -> imagem3

imagem1 %>%
  bind_rows(imagem2) %>%
  bind_rows(imagem3) -> all

```

&nbsp; 

#### Part B

&nbsp; 

```{r}
# look at percentage for total 
all %>%
  group_by(expert_text) %>%
  summarise(prop_total = round((n() / 345556),2))

# look at percentage for each one 
len1 <- nrow(imagem1)
imagem1 %>%
  group_by(expert_text) %>%
  summarise(prop_total = round((n() / len1),2))

len2 <- nrow(imagem2)
imagem2 %>%
  group_by(expert_text) %>%
  summarise(prop_total = round((n() / len2),2))

len3 <- nrow(imagem3)
imagem3 %>%
  group_by(expert_text) %>%
  summarise(prop_total = round((n() / len3),2))
```


```{r}

# We might want to change the colors here becuase it's hard to distinguish between the blue and the black on the legend

# Image 1
ggplot(imagem1, aes(x = x_coord, y = y_coord, color = expert_text)) + 
  geom_point() + 
  theme_settings + 
  labs(x = "X Coordinate", y = "Y Coordinate", color = "Expert Labels") +
  scale_colour_manual(values = c("darkblue", "black", "lightgrey"))

# Image 2
ggplot(imagem2, aes(x = x_coord, y = y_coord, color = expert_text)) + 
  geom_point() + 
  theme_settings + 
  labs(x = "X Coordinate", y = "Y Coordinate", color = "Expert Labels") +
  scale_colour_manual(values = c("darkblue", "black", "lightgrey"))

# Image 3
ggplot(imagem3, aes(x = x_coord, y = y_coord, color = expert_text)) + 
  geom_point() + 
  theme_settings + 
  labs(x = "X Coordinate", y = "Y Coordinate", color = "Expert Labels") +
  scale_colour_manual(values = c("darkblue", "black", "lightgrey"))
```

&nbsp; 

#### Part C

&nbsp; 

```{r}
# pairwise relationships between features 
# cor(all$ndai, all$corr)

all %>%
  select(ndai:angle_an) %>%
  ggpairs()
```

```{r}
# looking at al the angles 
# all %>%
#   select(angle_df:angle_an) %>%
#   ggpairs()
```


```{r}
# expert labels vs features 
imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = ndai, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = corr, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = sd, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = angle_df, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = angle_cf, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = angle_bf, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = angle_af, fill= expert)) +
  geom_histogram()

imagem1 %>%
  filter(expert != 0) %>%
  ggplot(aes(x = angle_an, fill= expert)) +
  geom_histogram()
```


## Section 2

#### Part A
```{r}
image1_x_min <- min(imagem1$x_coord)
image1_x_max <- max(imagem1$x_coord)
image1_x_step <- (image1_x_max-image1_x_min)/3
image_1_xcord_left <- rep(c(image1_x_min,image1_x_min+image1_x_step,image1_x_min+2*image1_x_step),3)
image_1_xcord_right <- rep(c(image1_x_min+image1_x_step-1,image1_x_min+2*image1_x_step-1,image1_x_max),3)
image1_y_min <- min(imagem1$y_coord)
image1_y_max <- max(imagem1$y_coord)
image1_y_step <- (image1_y_max-image1_y_min)/3
image_1_ycord_top <- c(rep(image1_y_min,3),rep(image1_y_min+image1_y_step,3),rep(image1_y_min+2*image1_y_step,3))
image_1_ycord_bot <- c(rep(image1_y_min+image1_y_step-1,3),rep(image1_y_min+2*image1_y_step-1,3),rep(image1_y_max,3))
image_1_blocks <- tibble(left = image_1_xcord_left, right = image_1_xcord_right,
                         top = image_1_ycord_top, bottom = image_1_ycord_bot)

image2_x_min <- min(imagem2$x_coord)
image2_x_max <- max(imagem2$x_coord)
image2_x_step <- floor((image2_x_max-image2_x_min)/3)
image_2_xcord_left <- rep(c(image2_x_min,image2_x_min+image2_x_step,image2_x_min+2*image2_x_step),3)
image_2_xcord_right <- rep(c(image2_x_min+image2_x_step-1,image2_x_min+2*image2_x_step-1,image2_x_max),3)
image2_y_min <- min(imagem2$y_coord)
image2_y_max <- max(imagem2$y_coord)
image2_y_step <- (image2_y_max-image2_y_min)/3
image_2_ycord_top <- c(rep(image2_y_min,3),rep(image2_y_min+image2_y_step,3),rep(image2_y_min+2*image2_y_step,3))
image_2_ycord_bot <- c(rep(image2_y_min+image2_y_step-1,3),rep(image2_y_min+2*image2_y_step-1,3),rep(image2_y_max,3))
image_2_blocks <- tibble(left = image_2_xcord_left, right = image_2_xcord_right,
                         top = image_2_ycord_top, bottom = image_2_ycord_bot)

image3_x_min <- min(imagem3$x_coord)
image3_x_max <- max(imagem3$x_coord)
image3_x_step <- floor((image3_x_max-image3_x_min)/3)
image_3_xcord_left <- rep(c(image3_x_min,image3_x_min+image3_x_step,image3_x_min+2*image3_x_step),3)
image_3_xcord_right <- rep(c(image3_x_min+image3_x_step-1,image3_x_min+2*image3_x_step-1,image3_x_max),3)
image3_y_min <- min(imagem3$y_coord)
image3_y_max <- max(imagem3$y_coord)
image3_y_step <- (image3_y_max-image3_y_min)/3
image_3_ycord_top <- c(rep(image3_y_min,3),rep(image3_y_min+image3_y_step,3),rep(image3_y_min+2*image3_y_step,3))
image_3_ycord_bot <- c(rep(image3_y_min+image3_y_step-1,3),rep(image3_y_min+2*image3_y_step-1,3),rep(image3_y_max,3))
image_3_blocks <- tibble(left = image_3_xcord_left, right = image_3_xcord_right,
                         top = image_3_ycord_top, bottom = image_3_ycord_bot)
```

```{r}
set.seed(513)
train_index_1 <- sample(1:9,5)
set.seed(513)
val_index_1 <- sample(setdiff(1:9,train_index_1),2)
test_index_1 <- setdiff(1:9, c(train_index_1,val_index_1))

set.seed(513)
train_index_2 <- sample(1:9,5)
set.seed(513)
val_index_2 <- sample(setdiff(1:9,train_index_2),2)
test_index_2 <- setdiff(1:9, c(train_index_2,val_index_2))

set.seed(513)
train_index_3 <- sample(1:9,5)
set.seed(513)
val_index_3 <- sample(setdiff(1:9,train_index_3),2)
test_index_3 <- setdiff(1:9, c(train_index_3,val_index_3))

train_blocks_1 <- image_1_blocks[train_index_1,]
val_blocks_1 <- image_1_blocks[val_index_1,]
test_blocks_1 <- image_1_blocks[test_index_1,]

train_blocks_2 <- image_2_blocks[train_index_2,]
val_blocks_2 <- image_2_blocks[val_index_2,]
test_blocks_2 <- image_2_blocks[test_index_2,]

train_blocks_3 <- image_3_blocks[train_index_3,]
val_blocks_3 <- image_3_blocks[val_index_3,]
test_blocks_3 <- image_3_blocks[test_index_3,]
```

```{r}
# sum of the length train/val/test equals length of dataset

train <- rbind(imagem1[imagem1$x_coord >= train_blocks_1[[1,1]] &
                         imagem1$x_coord <= train_blocks_1[[1,2]]&
                         imagem1$y_coord >= train_blocks_1[[1,3]]&
                         imagem1$y_coord <= train_blocks_1[[1,4]],],
               imagem1[imagem1$x_coord >= train_blocks_1[[2,1]] &
                         imagem1$x_coord <= train_blocks_1[[2,2]]&
                         imagem1$y_coord >= train_blocks_1[[2,3]]&
                         imagem1$y_coord <= train_blocks_1[[2,4]],],
               imagem1[imagem1$x_coord >= train_blocks_1[[3,1]] &
                         imagem1$x_coord <= train_blocks_1[[3,2]]&
                         imagem1$y_coord >= train_blocks_1[[3,3]]&
                         imagem1$y_coord <= train_blocks_1[[3,4]],],
               imagem1[imagem1$x_coord >= train_blocks_1[[4,1]] &
                         imagem1$x_coord <= train_blocks_1[[4,2]]&
                         imagem1$y_coord >= train_blocks_1[[4,3]]&
                         imagem1$y_coord <= train_blocks_1[[4,4]],],
               imagem1[imagem1$x_coord >= train_blocks_1[[5,1]] &
                         imagem1$x_coord <= train_blocks_1[[5,2]]&
                         imagem1$y_coord >= train_blocks_1[[5,3]]&
                         imagem1$y_coord <= train_blocks_1[[5,4]],],
               imagem2[imagem2$x_coord >= train_blocks_2[[1,1]] &
                         imagem2$x_coord <= train_blocks_2[[1,2]]&
                         imagem2$y_coord >= train_blocks_2[[1,3]]&
                         imagem2$y_coord <= train_blocks_2[[1,4]],],
               imagem2[imagem2$x_coord >= train_blocks_2[[2,1]] &
                         imagem2$x_coord <= train_blocks_2[[2,2]]&
                         imagem2$y_coord >= train_blocks_2[[2,3]]&
                         imagem2$y_coord <= train_blocks_2[[2,4]],],
               imagem2[imagem2$x_coord >= train_blocks_2[[3,1]] &
                         imagem2$x_coord <= train_blocks_2[[3,2]]&
                         imagem2$y_coord >= train_blocks_2[[3,3]]&
                         imagem2$y_coord <= train_blocks_2[[3,4]],],
               imagem2[imagem2$x_coord >= train_blocks_2[[4,1]] &
                         imagem2$x_coord <= train_blocks_2[[4,2]]&
                         imagem2$y_coord >= train_blocks_2[[4,3]]&
                         imagem2$y_coord <= train_blocks_2[[4,4]],],
               imagem2[imagem2$x_coord >= train_blocks_2[[5,1]] &
                         imagem2$x_coord <= train_blocks_2[[5,2]]&
                         imagem2$y_coord >= train_blocks_2[[5,3]]&
                         imagem2$y_coord <= train_blocks_2[[5,4]],],
               imagem3[imagem3$x_coord >= train_blocks_3[[1,1]] &
                         imagem3$x_coord <= train_blocks_3[[1,2]]&
                         imagem3$y_coord >= train_blocks_3[[1,3]]&
                         imagem3$y_coord <= train_blocks_3[[1,4]],],
               imagem3[imagem3$x_coord >= train_blocks_3[[2,1]] &
                         imagem3$x_coord <= train_blocks_3[[2,2]]&
                         imagem3$y_coord >= train_blocks_3[[2,3]]&
                         imagem3$y_coord <= train_blocks_3[[2,4]],],
               imagem3[imagem3$x_coord >= train_blocks_3[[3,1]] &
                         imagem3$x_coord <= train_blocks_3[[3,2]]&
                         imagem3$y_coord >= train_blocks_3[[3,3]]&
                         imagem3$y_coord <= train_blocks_3[[3,4]],],
               imagem3[imagem3$x_coord >= train_blocks_3[[4,1]] &
                         imagem3$x_coord <= train_blocks_3[[4,2]]&
                         imagem3$y_coord >= train_blocks_3[[4,3]]&
                         imagem3$y_coord <= train_blocks_3[[4,4]],],
               imagem3[imagem3$x_coord >= train_blocks_3[[5,1]] &
                         imagem3$x_coord <= train_blocks_3[[5,2]]&
                         imagem3$y_coord >= train_blocks_3[[5,3]]&
                         imagem3$y_coord <= train_blocks_3[[5,4]],])

val <- rbind(imagem1[imagem1$x_coord >= val_blocks_1[[1,1]] &
                         imagem1$x_coord <= val_blocks_1[[1,2]]&
                         imagem1$y_coord >= val_blocks_1[[1,3]]&
                         imagem1$y_coord <= val_blocks_1[[1,4]],],
               imagem1[imagem1$x_coord >= val_blocks_1[[2,1]] &
                         imagem1$x_coord <= val_blocks_1[[2,2]]&
                         imagem1$y_coord >= val_blocks_1[[2,3]]&
                         imagem1$y_coord <= val_blocks_1[[2,4]],],
               imagem2[imagem2$x_coord >= val_blocks_2[[1,1]] &
                         imagem2$x_coord <= val_blocks_2[[1,2]]&
                         imagem2$y_coord >= val_blocks_2[[1,3]]&
                         imagem2$y_coord <= val_blocks_2[[1,4]],],
               imagem2[imagem2$x_coord >= val_blocks_2[[2,1]] &
                         imagem2$x_coord <= val_blocks_2[[2,2]]&
                         imagem2$y_coord >= val_blocks_2[[2,3]]&
                         imagem2$y_coord <= val_blocks_2[[2,4]],],
               imagem3[imagem3$x_coord >= val_blocks_3[[1,1]] &
                         imagem3$x_coord <= val_blocks_3[[1,2]]&
                         imagem3$y_coord >= val_blocks_3[[1,3]]&
                         imagem3$y_coord <= val_blocks_3[[1,4]],],
               imagem3[imagem3$x_coord >= val_blocks_3[[2,1]] &
                         imagem3$x_coord <= val_blocks_3[[2,2]]&
                         imagem3$y_coord >= val_blocks_3[[2,3]]&
                         imagem3$y_coord <= val_blocks_3[[2,4]],])

test <- rbind(imagem1[imagem1$x_coord >= test_blocks_1[[1,1]] &
                         imagem1$x_coord <= test_blocks_1[[1,2]]&
                         imagem1$y_coord >= test_blocks_1[[1,3]]&
                         imagem1$y_coord <= test_blocks_1[[1,4]],],
               imagem1[imagem1$x_coord >= test_blocks_1[[2,1]] &
                         imagem1$x_coord <= test_blocks_1[[2,2]]&
                         imagem1$y_coord >= test_blocks_1[[2,3]]&
                         imagem1$y_coord <= test_blocks_1[[2,4]],],
               imagem2[imagem2$x_coord >= test_blocks_2[[1,1]] &
                         imagem2$x_coord <= test_blocks_2[[1,2]]&
                         imagem2$y_coord >= test_blocks_2[[1,3]]&
                         imagem2$y_coord <= test_blocks_2[[1,4]],],
               imagem2[imagem2$x_coord >= test_blocks_2[[2,1]] &
                         imagem2$x_coord <= test_blocks_2[[2,2]]&
                         imagem2$y_coord >= test_blocks_2[[2,3]]&
                         imagem2$y_coord <= test_blocks_2[[2,4]],],
               imagem3[imagem3$x_coord >= test_blocks_3[[1,1]] &
                         imagem3$x_coord <= test_blocks_3[[1,2]]&
                         imagem3$y_coord >= test_blocks_3[[1,3]]&
                         imagem3$y_coord <= test_blocks_3[[1,4]],],
               imagem3[imagem3$x_coord >= test_blocks_3[[2,1]] &
                         imagem3$x_coord <= test_blocks_3[[2,2]]&
                         imagem3$y_coord >= test_blocks_3[[2,3]]&
                         imagem3$y_coord <= test_blocks_3[[2,4]],])
```



```{r}
find_blocks <- function(x, y, num_blocks) {
  n <- sqrt(num_blocks)
  x_min <- min(x)
  x_max <- max(x)
  x_step <- (x_max-x_min)/n
  
  y_min <- min(y)
  y_max <- max(y)
  y_step <- (y_max-y_min)/n
  
  block <- tibble()
  names(block) <- c("top", "bottom", "left", "right")
  
  for (i in seq_len(n)) {
    # make top and bottom
    top <- floor(y_min + (i-1) * y_step)
    bot <- floor(y_max - (n-i) * y_step )
    if (i != n)
      bot <- bot - 1
    
    for (j in seq_len(n)){
      # make left and right 
      left <- floor(x_min + (j-1) * x_step)
      right <- floor(x_max - (n-j) * x_step )
      if (j != n)
        right <- right - 1
      
      block %>%
        bind_rows(data.frame(top, bot, left, right)) -> block 
    }
  }
  
  return(block)
}

# this is going to return overlapping intervals, so will need x >= top and x < bot, etc. 
```



```{r}
split_blocks <- function(block, num_blocks, train_num_blocks, val_num_blocks) {
  set.seed(513)
  train_index <- sample(seq_len(num_blocks),train_num_blocks)
  set.seed(513)
  val_index <- sample(setdiff(seq_len(num_blocks),train_index),val_num_blocks)
  test_index <- setdiff(seq_len(num_blocks), c(train_index,val_index))
  
  train_blocks <- block[train_index,]
  val_blocks <- block[val_index,]
  test_blocks <- block[test_index,]
  
  return(list(train = train_blocks, val = val_blocks, test = test_blocks))
}
```

```{r}
split_data <- function(data, block) {
  final_data <- tibble()
  for (i in seq_len(nrow(block))) {
    coords <- block[i,]
    
    data %>%
      filter(x_coord >= coords$left, x_coord <= coords$right,
            y_coord >= coords$top, y_coord <= coords$bot) -> filtered_data
        
    final_data <- rbind(final_data, filtered_data)
  }
  
  return(final_data)
}
```


```{r}
process_data_main <- function(df, num_blocks, train_num_blocks, val_num_blocks) {
  blocks <- find_blocks(df$x_coord, df$y_coord, num_blocks)
  block_indices <- split_blocks(blocks, num_blocks, train_num_blocks, val_num_blocks)
  
  val <- split_data(df, block_indices$val)
  test <- split_data(df, block_indices$test)
  train <- split_data(df, block_indices$train)

  return(list(val = val, test = test, train = train))
}
```


```{r}
image1_dfs <- process_data_main(imagem1, 9, 5, 2)
image1_test <- image1_dfs$test
image1_train <- image1_dfs$train
image1_val <- image1_dfs$val

image2_dfs <- process_data_main(imagem2, 9, 5, 2)
image2_test <- image2_dfs$test
image2_train <- image2_dfs$train
image2_val <- image2_dfs$val

image3_dfs <- process_data_main(imagem3, 9, 5, 2)
image3_test <- image3_dfs$test
image3_train <- image3_dfs$train
image3_val <- image3_dfs$val

train <- image1_train %>%
  bind_rows(image2_train) %>%
  bind_rows(image3_train)

test <- image1_test%>%
  bind_rows(image2_test) %>%
  bind_rows(image3_test)

val <- image1_val%>%
  bind_rows(image2_val) %>%
  bind_rows(image3_val)

# 345556
# nrow(train) + nrow(test) + nrow(val)
```
























